/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
import java.util.UUID

import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner
import org.scalatest.{FlatSpec, Matchers}

@RunWith(classOf[JUnitRunner])
class NewTypeUsageSpecs extends FlatSpec with Matchers {
  import NewTypeUsage._

  behavior of "@newtype case class"

  it should "generate a type alias, companion object, and constructor" in {

    // Ensure that we can access the type and the constructor.
    val uuid = UUID.randomUUID()
    val sut = OrderId(uuid)
    assertCompiles("sut: OrderId")

    // Should have the same runtime representation as Int.
    sut should (be (uuid) and be (OrderId(uuid)))
  }

  it should "generate a text extension method" in {
    val sut = OrderId(UUID.randomUUID())
    val expected = s"ORDER:${sut.value}"
    val actual = sut.text

    actual shouldBe expected
  }
}
